# Generated by Django 2.2.4 on 2023-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(max_length=9)),
                ('product_name', models.TextField(max_length=255)),
                ('item_condition_id', models.IntegerField(max_length=2)),
                ('category', models.TextField(max_length=500)),
                ('shipping', models.IntegerField(max_length=2)),
                ('price', models.FloatField(max_length=9)),
                ('item_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
